### ISSUE TITLE
bundle install --path=vendor/bundleで失敗

### ISSUE THREAD

**Issue by kurotaky** [kurotaky/scores#3]
bundle install --path=vendor/bundle したら以下のエラー

```
    --with-zlib-include
    --without-zlib-include=${zlib-dir}/include
    --with-zlib-lib
    --without-zlib-lib=${zlib-dir}/lib
    --with-iconv-dir
    --without-iconv-dir
    --with-iconv-include
    --without-iconv-include=${iconv-dir}/include
    --with-iconv-lib
    --without-iconv-lib=${iconv-dir}/lib
    --with-xml2-dir
    --without-xml2-dir
    --with-xml2-include
    --without-xml2-include=${xml2-dir}/include
    --with-xml2-lib
    --without-xml2-lib=${xml2-dir}/lib
    --with-xslt-dir
    --without-xslt-dir
    --with-xslt-include
    --without-xslt-include=${xslt-dir}/include
    --with-xslt-lib
    --without-xslt-lib=${xslt-dir}/lib
    --with-libxslt-config
    --without-libxslt-config
    --with-pkg-config
    --without-pkg-config
    --with-libxml-2.0-config
    --without-libxml-2.0-config
    --with-libiconv-config
    --without-libiconv-config
/Users/k251/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/mkmf.rb:430:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /Users/k251/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/mkmf.rb:561:in `try_cpp'
    from /Users/k251/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/mkmf.rb:1085:in `block in find_header'
    from /Users/k251/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/mkmf.rb:891:in `block in checking_for'
    from /Users/k251/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/mkmf.rb:336:in `block (2 levels) in postpone'
    from /Users/k251/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/mkmf.rb:306:in `open'
    from /Users/k251/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/mkmf.rb:336:in `block in postpone'
    from /Users/k251/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/mkmf.rb:306:in `open'
    from /Users/k251/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/mkmf.rb:332:in `postpone'
    from /Users/k251/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/mkmf.rb:890:in `checking_for'
    from /Users/k251/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/mkmf.rb:1084:in `find_header'
    from extconf.rb:166:in `<main>'


Gem files will remain installed in /Users/k251/heteml_project/admin/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.0 for inspection.
Results logged to /Users/k251/heteml_project/admin/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.0/ext/nokogiri/gem_make.out

An error occurred while installing nokogiri (1.6.0), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.0'` succeeds before bundling.
```

**Comment by kurotaky** [comment]
gcc-4.2 のシンボリックリンクを作成

```
/Users/k251/project/admin% sudo ln -s /usr/bin/gcc /usr/bin/gcc-4.2

/Users/k251/project/admin% ll /usr/bin/gcc
-rwxr-xr-x  1 root  admin  35472 10  7 09:28 /usr/bin/gcc

/Users/k251/project/admin% ll /usr/bin/gcc-4.2
lrwxr-xr-x  1 root  wheel  12 11  6 11:07 /usr/bin/gcc-4.2 -> /usr/bin/gcc
```

もう一回 bundle install 

```
bundle install --path=vendor/bundle
```

解決できた

```
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Using addressable (2.3.5)
Using mime-types (2.0)
Using mini_portile (0.5.2)
Installing nokogiri (1.6.0)
Installing rack (1.5.2)
Installing rack-test (0.6.2)
Installing xpath (2.0.0)
Installing capybara (2.1.0)
Installing json (1.8.1)
Installing capybara-webkit (1.0.0)
Installing ffi (1.9.3)
Installing childprocess (0.3.9)
Installing diff-lcs (1.2.4)
Installing launchy (2.3.0)
Installing multi_json (1.8.2)
Installing rspec-core (2.14.7)
Installing rspec-expectations (2.14.3)
Installing rspec-mocks (2.14.4)
Installing rspec (2.14.1)
Installing rubyzip (1.0.0)
Installing websocket (1.0.7)
Installing selenium-webdriver (2.37.0)
Using bundler (1.3.5)
Your bundle is complete!
It was installed into ./vendor/bundle
```

参考
- http://stackoverflow.com/questions/12657558/installing-nokogiri-mac-os-x-10-8-2-xcode-installed
- http://blog.takapra.com/index.php/2013/04/21/ruby-bundler-basic/
